CREATE TABLE IF NOT EXISTS certificates (
  id TEXT PRIMARY KEY,
  register_no TEXT,
  name TEXT NOT NULL,
  institution TEXT NOT NULL,
  issueDate TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS openai_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  openai_key TEXT NOT NULL,
  used BOOLEAN DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
